// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: active_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActiveOrder = `-- name: CreateActiveOrder :one
INSERT INTO active_orders (id, side, qty, leaves_qty, price, instrument)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, side, qty, leaves_qty, price, instrument
`

type CreateActiveOrderParams struct {
	ID         string         `json:"id"`
	Side       string         `json:"side"`
	Qty        pgtype.Numeric `json:"qty"`
	LeavesQty  pgtype.Numeric `json:"leaves_qty"`
	Price      pgtype.Numeric `json:"price"`
	Instrument string         `json:"instrument"`
}

func (q *Queries) CreateActiveOrder(ctx context.Context, arg CreateActiveOrderParams) (ActiveOrder, error) {
	row := q.db.QueryRow(ctx, createActiveOrder,
		arg.ID,
		arg.Side,
		arg.Qty,
		arg.LeavesQty,
		arg.Price,
		arg.Instrument,
	)
	var i ActiveOrder
	err := row.Scan(
		&i.ID,
		&i.Side,
		&i.Qty,
		&i.LeavesQty,
		&i.Price,
		&i.Instrument,
	)
	return i, err
}

const deleteActiveOrder = `-- name: DeleteActiveOrder :one
DELETE
FROM active_orders
WHERE id = $1 RETURNING id, side, qty, leaves_qty, price, instrument
`

func (q *Queries) DeleteActiveOrder(ctx context.Context, id string) (ActiveOrder, error) {
	row := q.db.QueryRow(ctx, deleteActiveOrder, id)
	var i ActiveOrder
	err := row.Scan(
		&i.ID,
		&i.Side,
		&i.Qty,
		&i.LeavesQty,
		&i.Price,
		&i.Instrument,
	)
	return i, err
}

const getActiveOrder = `-- name: GetActiveOrder :one
SELECT id, side, qty, leaves_qty, price, instrument
FROM active_orders
WHERE id = $1
`

func (q *Queries) GetActiveOrder(ctx context.Context, id string) (ActiveOrder, error) {
	row := q.db.QueryRow(ctx, getActiveOrder, id)
	var i ActiveOrder
	err := row.Scan(
		&i.ID,
		&i.Side,
		&i.Qty,
		&i.LeavesQty,
		&i.Price,
		&i.Instrument,
	)
	return i, err
}

const listActiveOrders = `-- name: ListActiveOrders :many
SELECT id, side, qty, leaves_qty, price, instrument
FROM active_orders
ORDER BY id
`

func (q *Queries) ListActiveOrders(ctx context.Context) ([]ActiveOrder, error) {
	rows, err := q.db.Query(ctx, listActiveOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveOrder{}
	for rows.Next() {
		var i ActiveOrder
		if err := rows.Scan(
			&i.ID,
			&i.Side,
			&i.Qty,
			&i.LeavesQty,
			&i.Price,
			&i.Instrument,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActiveOrder = `-- name: UpdateActiveOrder :one
UPDATE active_orders
SET side       = COALESCE($2, side),
    qty        = COALESCE($3, qty),
    leaves_qty = COALESCE($4, leaves_qty),
    price      = COALESCE($5, price)
WHERE id = $1 RETURNING id, side, qty, leaves_qty, price, instrument
`

type UpdateActiveOrderParams struct {
	ID        string         `json:"id"`
	Side      pgtype.Text    `json:"side"`
	Qty       pgtype.Numeric `json:"qty"`
	LeavesQty pgtype.Numeric `json:"leaves_qty"`
	Price     pgtype.Numeric `json:"price"`
}

func (q *Queries) UpdateActiveOrder(ctx context.Context, arg UpdateActiveOrderParams) (ActiveOrder, error) {
	row := q.db.QueryRow(ctx, updateActiveOrder,
		arg.ID,
		arg.Side,
		arg.Qty,
		arg.LeavesQty,
		arg.Price,
	)
	var i ActiveOrder
	err := row.Scan(
		&i.ID,
		&i.Side,
		&i.Qty,
		&i.LeavesQty,
		&i.Price,
		&i.Instrument,
	)
	return i, err
}
