// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveOrder struct {
	ID        string         `json:"id"`
	Side      string         `json:"side"`
	Qty       pgtype.Numeric `json:"qty"`
	LeavesQty pgtype.Numeric `json:"leaves_qty"`
	Price     pgtype.Numeric `json:"price"`
}

type Event struct {
	ID        uuid.UUID      `json:"id"`
	OrderID   string         `json:"order_id"`
	Timestamp time.Time      `json:"timestamp"`
	Type      string         `json:"type"`
	Side      string         `json:"side"`
	OrderQty  pgtype.Numeric `json:"order_qty"`
	LeavesQty pgtype.Numeric `json:"leaves_qty"`
	ExecQty   pgtype.Numeric `json:"exec_qty"`
	Price     pgtype.Numeric `json:"price"`
}
