// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActiveOrder struct {
	ID          string         `json:"id"`
	Side        string         `json:"side"`
	OrderQty    pgtype.Numeric `json:"order_qty"`
	LeavesQty   pgtype.Numeric `json:"leaves_qty"`
	Price       pgtype.Numeric `json:"price"`
	Instrument  string         `json:"instrument"`
	ExecType    string         `json:"exec_type"`
	CumQty      pgtype.Numeric `json:"cum_qty"`
	OrderStatus string         `json:"order_status"`
}

type Trade struct {
	ID            string         `json:"id"`
	BuyerOrderID  string         `json:"buyer_order_id"`
	SellerOrderID string         `json:"seller_order_id"`
	Qty           pgtype.Numeric `json:"qty"`
	Price         pgtype.Numeric `json:"price"`
	Instrument    string         `json:"instrument"`
}
