// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	DeleteExecution(ctx context.Context, execID string) (Execution, error)
	DeleteTrade(ctx context.Context, tradeReportID string) (Trade, error)
	GetExecution(ctx context.Context, execID string) (Execution, error)
	GetTrade(ctx context.Context, tradeReportID string) (Trade, error)
	ListExecutions(ctx context.Context) ([]Execution, error)
	ListTrades(ctx context.Context) ([]Trade, error)
	UpdateExecution(ctx context.Context, arg UpdateExecutionParams) (Execution, error)
	UpdateTrade(ctx context.Context, arg UpdateTradeParams) (Trade, error)
}

var _ Querier = (*Queries)(nil)
